local parser = clink.arg.new_parser
local anaconda_parser = parser(
   {
      "clean" .. parser(
	 "-h", "--help",
	 "-a", "--all",
	 "-i", "--index-cache",
	 "-p", "--packages",
	 "-t", "--tarballs",
	 "-f", "--force-pkgs-dirs",
	 "-c", "--tempfiles",
	 "-d", "--dry-run",
	 "--json",
	 "-q", "--quiet",
	 "-v", "--verbose",
	 "-y", "--yes"
		       ), 
      "config" .. parser(
	 "-h", "--help",
	 "--json",
	 "-v", "--verbose",
	 "-q", "--quiet",
	 "--system",
	 "--env",
	 "--file",
	 "--show",
	 "--show-sources",
	 "--validate",
	 "--describe",
	 "--write-default",
	 "--get",
	 "--append",
	 "--prepend", "--add",
	 "--set",
	 "--remove",
	 "--remove-key",
	 "--stdin"
			),
      "create" .. parser("-h", "--help",
			 "--clone",
			 "--file",
			 "-n", "--name",
			 "-p", "--prefix",
			 "-c", "--channel",
			 "--use-local",
			 "--override-channels",
			 "--repodata-fn",
			 "--strict-channel-priorit",
			 "--no-channel-priorit",
			 "--no-deps",
			 "--only-deps",
			 "--no-pin",
			 "--no-default-package",
			 "--copy",
			 "--no-shortcuts",
			 "-C", "--use-index-cach",
			 "-k", "--insecure",
			 "--offline",
			 "-d", "--dry-run",
			 "--json",
			 "-q", "--quiet",
			 "-v", "--verbose",
			 "-y", "--yes",
			 "--download-only",
			 "--show-channel-urls"),
      "help",
      "info" .. parser(
	 "-h", "--help",
	 "-a", "--all",
	 "--base",
	 "-e", "--envs",
	 "-s", "--system",
	 "--unsafe-channels",
	 "--json",
	 "-v", "--verbose",
	 "-q", "--quiet"
		      ),
      "init" .. parser(
	 "-h", "--help",
	 "--all",
	 "--anaconda-prompt",
	 "-d", "--dry-run",
	 "--reverse",
	 "--json",
	 "-v", "--verbose",
	 "-q", "--quiet"
		      ),
      "install" .. parser("-h", "--help",
			  "--revision",
			  "--file",
			  "--dev",
			  "-n", "--name",
			  "-p", "--prefix",
			  "-c", "--channel",
			  "--use-local",
			  "--override-channels",
			  "--repodata-fn",
			  "--strict-channel-priority",
			  "--no-channel-priority",
			  "--no-deps",
			  "--only-deps",
			  "--no-pin",
			  "--force-reinstall",
			  "--freeze-installed", "--no-update-deps",
			  "--update-deps",
			  "-S", "--satisfied-skip-solve",
			  "--update-all", "--all",
			  "--update-specs",
			  "--copy",
			  "--no-shortcuts",
			  "-m", "--mkdir",
			  "--clobber",
			  "-C", "--use-index-cache",
			  "-k", "--insecure",
			  "--offline",
			  "-d", "--dry-run",
			  "--json",
			  "-q", "--quiet",
			  "-v", "--verbose",
			  "-y", "--yes",
			  "--download-only",
			  "--show-channel-urls"),
      "list" .. parser(
	 "-h", "--help",
	 "--show-channel-urls",
	 "-c", "--canonical",
	 "-f", "--full-name",
	 "--explicit",
	 "--md5",
	 "-e", "--export",
	 "-r", "--revisions",
	 "--no-pip",
	 "-n ", "--name",
	 "-p PATH", "--prefix PATH",
	 "--json",
	 "-v", "--verbose",
	 "-q", "--quiet"
		      ),
      "package" .. parser(
	 "-h", "--help",
	 "-w", "--which",
	 "-r", "--reset",
	 "-u", "--untracked",
	 "--pkg-name",
	 "--pkg-version",
	 "--pkg-build",
	 "-n", "--name",
	 "-p", "--prefix"
			 ),
      "remove" .. parser(
	 "-h", "--help",
	 "--dev",
	 "-n", "--name",
	 "-p", "--prefix",
	 "-c", "--channel",
	 "--use-local",
	 "--override-channels",
	 "--repodata-fn",
	 "--all",
	 "--features",
	 "--force-remove", "--force",
	 "--no-pin",
	 "-C", "--use-index-cache",
	 "-k", "--insecure",
	 "--offline",
	 "-d", "--dry-run",
	 "--json",
	 "-q", "--quiet",
	 "-v", "--verbose",
	 "-y", "--yes"
			),
      "uninstall" .. parser(
	 "-h", "--help",
	 "--dev",
	 "-n", "--name",
	 "-p", "--prefix",
	 "-c", "--channel",
	 "--use-local",
	 "--override-channels",
	 "--repodata-fn",
	 "--all",
	 "--features",
	 "--force-remove", "--force",
	 "--no-pin",
	 "-C", "--use-index-cache",
	 "-k", "--insecure",
	 "--offline",
	 "-d", "--dry-run",
	 "--json",
	 "-q", "--quiet",
	 "-v", "--verbose",
	 "-y", "--yes"
			   ),
      "run" .. parser(
	 "-h", "--help",
	 "-v", "--verbose",
	 "--dev",
	 "--debug-wrapper-scripts",
	 "--cwd",
	 "-n", "--name",
	 "-p", "--prefix"

		     ),
      "search" .. parser("-h", "--help",
			 "--envs",
			 "-i", "--info",
			 "--subdir", "--platform",
			 "-c", "--channel",
			 "--use-local",
			 "--override-channels",
			 "--repodata-fn",
			 "-C", "--use-index-cache",
			 "-k", "--insecure",
			 "--offline",
			 "--json",
			 "-v", "--verbose",
			 "-q", "--quiet"
			),
      "update" .. parser("-h", "--help",
			 "--file",
			 "-n", "--name",
			 "-p", "--prefix",
			 "-c", "--channel",
			 "--use-local",
			 "--override-channels",
			 "--repodata-fn",
			 "--strict-channel-priority",
			 "--no-channel-priority",
			 "--no-deps",
			 "--only-deps",
			 "--no-pin",
			 "--force-reinstall",
			 "--freeze-installed", "--no-update-deps",
			 "--update-deps",
			 "-S", "--satisfied-skip-solve",
			 "--update-all", "--all",
			 "--update-specs",
			 "--copy",
			 "--no-shortcuts",
			 "--clobber",
			 "-C", "--use-index-cache",
			 "-k", "--insecure",
			 "--offline",
			 "-d", "--dry-run",
			 "--json",
			 "-q", "--quiet",
			 "-v", "--verbose",
			 "-y", "--yes",
			 "--download-only",
			 "--show-channel-urls"),
      "upgrade" .. parser("-h", "--help",
			  "--file FILE",
			  "-n", "--name",
			  "-p", "--prefix",
			  "-c", "--channel",
			  "--use-local",
			  "--override-channels",
			  "--repodata-fn",
			  "--strict-channel-priority",
			  "--no-channel-priority",
			  "--no-deps",
			  "--only-deps",
			  "--no-pin",
			  "--force-reinstall",
			  "--freeze-installed", "--no-update-deps",
			  "--update-deps",
			  "-S", "--satisfied-skip-solve",
			  "--update-all", "--all",
			  "--update-specs",
			  "--copy",
			  "--no-shortcuts",
			  "--clobber",
			  "-C", "--use-index-cache",
			  "-k", "--insecure",
			  "--offline",
			  "-d", "--dry-run",
			  "--json",
			  "-q", "--quiet",
			  "-v", "--verbose",
			  "-y", "--yes",
			  "--download-only",
			  "--show-channel-urls"),
      "--help",
      "-h",
      "env" .. parser({
	    "create" .. parser("-h", "--help",
			       "-f", "--file",
			       "--force",
			       "-n", "--name",
			       "-p", "--prefix",
			       "-C", "--use-index-cache",
			       "-k", "--insecure",
			       "--offline",
			       "--json",
			       "-v", "--verbose",
			       "-q", "--quiet"),
	    "export" .. parser("-h", "--help",
			       "-c", "--channel",
			       "--override-channels",
			       "-f", "--file",
			       "--no-builds",
			       "--ignore-channels",
			       "--from-history",
			       "-n", "--name",
			       "-p", "--prefix",
			       "--json",
			       "-v", "--verbose",
			       "-q", "--quiet"),

	    "list" .. parser("-h", "--help", "--json", "-v", "--verbose", "-q", "--quiet"),

	    "remove" .. parser("-h", "--help", "-n", "--name", "-p",
			       "--prefix", "-d", "--dry-run", "--json", "-q", "--quiet",
			       "-v", "--verbose", "-y", "--yes"),

	    "update" .. parser("-h", "--help", "-f", "--file",
			       "--prune", "-n", "--name", "-p", "--prefix", "--json",
			       "-v", "--verbose", "-q", "--quiet"),

	    "config" .. parser("-h", "--help"),
	    "--help",
	    "-h"
		     }),
      "activate",
      "deactivate"
   }
)

clink.arg.register_parser("conda", anaconda_parser)

