--------------------------------------------------------------------------------
-- Clink argmatcher for cp (GNU coreutils)
--

clink.argmatcher("cp")
:adddescriptions({
    ["-r"] = { "Copy directories recursively" },
    ["-R"] = { "Copy directories recursively" },
    ["--recursive"] = { "Copy directories recursively" },
    ["-f"] = { "If an existing destination file cannot be opened, remove it and try again" },
    ["--force"] = { "If an existing destination file cannot be opened, remove it and try again" },
    ["-i"] = { "Prompt before overwrite" },
    ["--interactive"] = { "Prompt before overwrite" },
    ["-n"] = { "Do not overwrite an existing file" },
    ["--no-clobber"] = { "Do not overwrite an existing file" },
    ["-v"] = { "Explain what is being done" },
    ["--verbose"] = { "Explain what is being done" },
    ["-u"] = { "Copy only when the source is newer than the destination" },
    ["--update"] = { "Copy only when the source is newer than the destination" },
    ["-p"] = { "Preserve file attributes (mode, ownership, timestamps)" },
    ["--preserve"] = { "Preserve file attributes (mode, ownership, timestamps)" },
    ["-a"] = { "Archive mode; same as -dR --preserve=all" },
    ["--archive"] = { "Archive mode; same as -dR --preserve=all" },
    ["-l"] = { "Hard link files instead of copying" },
    ["--link"] = { "Hard link files instead of copying" },
    ["-s"] = { "Make symbolic links instead of copying" },
    ["--symbolic-link"] = { "Make symbolic links instead of copying" },
    ["-T"] = { "Treat destination as a normal file" },
    ["--no-target-directory"] = { "Treat destination as a normal file" },
    ["-t"] = { " arg", "Copy all sources into DIRECTORY" },
    ["--target-directory"] = { " arg", "Copy all sources into DIRECTORY" },
    ["-b"] = { "Make a backup of each existing destination file" },
    ["--backup"] = { "Make a backup of each existing destination file" },
    ["-d"] = { "Same as --no-dereference --preserve=links" },
    ["-P"] = { "Never follow symbolic links" },
    ["--no-dereference"] = { "Never follow symbolic links" },
    ["--parents"] = { "Use full source file name under DIRECTORY" },
    ["--strip-trailing-slashes"] = { "Remove any trailing slashes from each source argument" },
    ["--help"] = { "Display help and exit" },
    ["--version"] = { "Output version information and exit" },
})
:addflags({
    "-r", "-R", "--recursive",
    "-f", "--force",
    "-i", "--interactive",
    "-n", "--no-clobber",
    "-v", "--verbose",
    "-u", "--update",
    "-p", "--preserve",
    "-a", "--archive",
    "-l", "--link",
    "-s", "--symbolic-link",
    "-T", "--no-target-directory",
    "-t"..(clink.argmatcher():addarg(clink.dirmatches)),
    "--target-directory="..(clink.argmatcher():addarg(clink.dirmatches)),
    "-b", "--backup",
    "-d",
    "-P", "--no-dereference",
    "--parents",
    "--strip-trailing-slashes",
    "--help", "--version",
})
