--------------------------------------------------------------------------------
-- Docker daemon (`dockerd`) completions for Clink.
--
-- https://docs.docker.com/reference/cli/dockerd/

-- luacheck: no max line length

local function try_require(module)
    local r
    pcall(function() r = require(module) end)
    return r
end

try_require("arghelper")

--------------------------------------------------------------------------------
-- Value matchers for flags that accept arguments.

local log_levels = clink.argmatcher():addarg({"debug", "info", "warn", "error", "fatal"})
local log_drivers = clink.argmatcher():addarg({
    "none", "local", "json-file", "syslog", "journald", "gelf",
    "fluentd", "awslogs", "splunk", "etwlogs", "gcplogs", "logentries",
})
local storage_drivers = clink.argmatcher():addarg({
    "overlay2", "fuse-overlayfs", "btrfs", "zfs", "vfs",
})
local cgroup_drivers = clink.argmatcher():addarg({"cgroupfs", "systemd", "none"})
local seccomp_profiles = clink.argmatcher():addarg(clink.filematches)
local empty_arg = clink.argmatcher():addarg({})
local file_matcher = clink.argmatcher():addarg(clink.filematches)
local dir_matcher = clink.argmatcher():addarg(clink.dirmatches)

--------------------------------------------------------------------------------
-- Main argmatcher.

local dockerd = clink.argmatcher("dockerd")

dockerd:adddescriptions({
    ["--add-runtime"]               = { " runtime", "Register an additional OCI compatible runtime" },
    ["--allow-nondistributable-artifacts"] = { " list", "Allow push of nondistributable artifacts to registry" },
    ["--api-cors-header"]           = { " string", "Set CORS headers in the Engine API" },
    ["--authorization-plugin"]      = { " list", "Authorization plugins to load" },
    ["-b"]                          = { " string", "Attach containers to a network bridge" },
    ["--bridge"]                    = { " string", "Attach containers to a network bridge" },
    ["--bip"]                       = { " string", "Specify network bridge IP" },
    ["--cgroup-parent"]             = { " string", "Set parent cgroup for all containers" },
    ["--config-file"]               = { " string", "Daemon configuration file" },
    ["--containerd"]                = { " string", "containerd grpc address" },
    ["--containerd-namespace"]      = { " string", "Containerd namespace to use" },
    ["--containerd-plugins-namespace"] = { " string", "Containerd namespace to use for plugins" },
    ["--cpu-rt-period"]             = { " int", "Limit the CPU real-time period in microseconds" },
    ["--cpu-rt-runtime"]            = { " int", "Limit the CPU real-time runtime in microseconds" },
    ["--cri-containerd"]            = { "Start containerd with cri" },
    ["-D"]                          = { "Enable debug mode" },
    ["--debug"]                     = { "Enable debug mode" },
    ["--data-root"]                 = { " string", "Root directory of persistent Docker state" },
    ["--default-address-pool"]      = { " list", "Default address pools for node specific local networks" },
    ["--default-cgroupns-mode"]     = { " string", "Default mode for containers cgroup namespace" },
    ["--default-gateway"]           = { " ip", "Container default gateway IPv4 address" },
    ["--default-gateway-v6"]        = { " ip", "Container default gateway IPv6 address" },
    ["--default-ipc-mode"]          = { " string", "Default mode for containers ipc" },
    ["--default-network-opt"]       = { " map", "Default network options" },
    ["--default-runtime"]           = { " string", "Default OCI runtime for containers" },
    ["--default-shm-size"]          = { " bytes", "Default shm size for containers" },
    ["--default-ulimit"]            = { " ulimit", "Default ulimits for containers" },
    ["--dns"]                       = { " list", "DNS server to use" },
    ["--dns-opt"]                   = { " list", "DNS options to use" },
    ["--dns-search"]                = { " list", "DNS search domains to use" },
    ["--exec-opt"]                  = { " list", "Runtime execution options" },
    ["--exec-root"]                 = { " string", "Root directory for execution state files" },
    ["--experimental"]              = { "Enable experimental features" },
    ["--fixed-cidr"]                = { " string", "IPv4 subnet for fixed IPs" },
    ["--fixed-cidr-v6"]             = { " string", "IPv6 subnet for fixed IPs" },
    ["-G"]                          = { " string", "Group for the unix socket" },
    ["--group"]                     = { " string", "Group for the unix socket" },
    ["-H"]                          = { " list", "Daemon socket(s) to connect to" },
    ["--host"]                      = { " list", "Daemon socket(s) to connect to" },
    ["--help"]                      = { "Print usage" },
    ["--http-proxy"]                = { " string", "HTTP proxy URL for pulling images" },
    ["--https-proxy"]               = { " string", "HTTPS proxy URL for pulling images" },
    ["--icc"]                       = { "Enable inter-container communication" },
    ["--init"]                      = { "Run an init in the container to forward signals and reap processes" },
    ["--init-path"]                 = { " string", "Path to the docker-init binary" },
    ["--insecure-registry"]         = { " list", "Enable insecure registry communication" },
    ["--ip"]                        = { " ip", "Default IP when binding container ports" },
    ["--ip-forward"]                = { "Enable net.ipv4.ip_forward" },
    ["--ip-masq"]                   = { "Enable IP masquerading" },
    ["--ip6tables"]                 = { "Enable addition of ip6tables rules" },
    ["--iptables"]                  = { "Enable addition of iptables rules" },
    ["--ipv6"]                      = { "Enable IPv6 networking" },
    ["-l"]                          = { " string", "Set the logging level" },
    ["--log-level"]                 = { " string", "Set the logging level" },
    ["--label"]                     = { " list", "Set key=value labels to the daemon" },
    ["--live-restore"]              = { "Enable live restore of docker when containers are still running" },
    ["--log-driver"]                = { " string", "Default driver for container logs" },
    ["--log-opt"]                   = { " map", "Default log driver options for containers" },
    ["--max-concurrent-downloads"]  = { " int", "Set the max concurrent downloads" },
    ["--max-concurrent-uploads"]    = { " int", "Set the max concurrent uploads" },
    ["--max-download-attempts"]     = { " int", "Set the max download attempts for each pull" },
    ["--metrics-addr"]              = { " string", "Set default address and port to serve the metrics API on" },
    ["--mtu"]                       = { " int", "Set the containers network MTU" },
    ["--network-control-plane-mtu"] = { " int", "Network Control plane MTU" },
    ["--no-new-privileges"]         = { "Set no-new-privileges by default for new containers" },
    ["--no-proxy"]                  = { " string", "Comma-separated list of hosts or IP addresses for which the proxy is skipped" },
    ["--node-generic-resource"]     = { " list", "Advertise user-defined resource" },
    ["--oom-score-adjust"]          = { " int", "Set the oom_score_adj for the daemon" },
    ["-p"]                          = { " string", "Path to use for daemon PID file" },
    ["--pidfile"]                   = { " string", "Path to use for daemon PID file" },
    ["--raw-logs"]                  = { "Full timestamps without ANSI coloring" },
    ["--registry-mirror"]           = { " list", "Preferred registry mirror" },
    ["--rootless"]                  = { "Enable rootless mode" },
    ["--seccomp-profile"]           = { " string", "Path to seccomp profile" },
    ["--selinux-enabled"]           = { "Enable selinux support" },
    ["--shutdown-timeout"]          = { " int", "Set the default shutdown timeout" },
    ["-s"]                          = { " string", "Storage driver to use" },
    ["--storage-driver"]            = { " string", "Storage driver to use" },
    ["--storage-opt"]               = { " list", "Storage driver options" },
    ["--swarm-default-advertise-addr"] = { " string", "Set default address or interface for swarm advertised address" },
    ["--tls"]                       = { "Use TLS; implied by --tlsverify" },
    ["--tlscacert"]                 = { " string", "Trust certs signed only by this CA" },
    ["--tlscert"]                   = { " string", "Path to TLS certificate file" },
    ["--tlskey"]                    = { " string", "Path to TLS key file" },
    ["--tlsverify"]                 = { "Use TLS and verify the remote" },
    ["--userland-proxy"]            = { "Use userland proxy for loopback traffic" },
    ["--userland-proxy-path"]       = { " string", "Path to the userland proxy binary" },
    ["--userns-remap"]              = { " string", "User/Group setting for user namespaces" },
    ["-v"]                          = { "Print version information and quit" },
    ["--version"]                   = { "Print version information and quit" },
    ["--validate"]                  = { "Validate daemon configuration and exit" },
})

dockerd:addflags({
    "--add-runtime"                     .. empty_arg,
    "--allow-nondistributable-artifacts" .. empty_arg,
    "--api-cors-header"                 .. empty_arg,
    "--authorization-plugin"            .. empty_arg,
    "-b"                                .. empty_arg,
    "--bridge"                          .. empty_arg,
    "--bip"                             .. empty_arg,
    "--cgroup-parent"                   .. empty_arg,
    "--config-file"                     .. file_matcher,
    "--containerd"                      .. empty_arg,
    "--containerd-namespace"            .. empty_arg,
    "--containerd-plugins-namespace"    .. empty_arg,
    "--cpu-rt-period"                   .. empty_arg,
    "--cpu-rt-runtime"                  .. empty_arg,
    "--cri-containerd",
    "-D",
    "--debug",
    "--data-root"                       .. dir_matcher,
    "--default-address-pool"            .. empty_arg,
    "--default-cgroupns-mode"           .. clink.argmatcher():addarg({"host", "private"}),
    "--default-gateway"                 .. empty_arg,
    "--default-gateway-v6"              .. empty_arg,
    "--default-ipc-mode"                .. clink.argmatcher():addarg({"shareable", "private"}),
    "--default-network-opt"             .. empty_arg,
    "--default-runtime"                 .. empty_arg,
    "--default-shm-size"                .. empty_arg,
    "--default-ulimit"                  .. empty_arg,
    "--dns"                             .. empty_arg,
    "--dns-opt"                         .. empty_arg,
    "--dns-search"                      .. empty_arg,
    "--exec-opt"                        .. empty_arg,
    "--exec-root"                       .. dir_matcher,
    "--experimental",
    "--fixed-cidr"                      .. empty_arg,
    "--fixed-cidr-v6"                   .. empty_arg,
    "-G"                                .. empty_arg,
    "--group"                           .. empty_arg,
    "-H"                                .. empty_arg,
    "--host"                            .. empty_arg,
    "--help",
    "--http-proxy"                      .. empty_arg,
    "--https-proxy"                     .. empty_arg,
    "--icc",
    "--init",
    "--init-path"                       .. file_matcher,
    "--insecure-registry"               .. empty_arg,
    "--ip"                              .. empty_arg,
    "--ip-forward",
    "--ip-masq",
    "--ip6tables",
    "--iptables",
    "--ipv6",
    "-l"                                .. log_levels,
    "--log-level"                       .. log_levels,
    "--label"                           .. empty_arg,
    "--live-restore",
    "--log-driver"                      .. log_drivers,
    "--log-opt"                         .. empty_arg,
    "--max-concurrent-downloads"        .. empty_arg,
    "--max-concurrent-uploads"          .. empty_arg,
    "--max-download-attempts"           .. empty_arg,
    "--metrics-addr"                    .. empty_arg,
    "--mtu"                             .. empty_arg,
    "--network-control-plane-mtu"       .. empty_arg,
    "--no-new-privileges",
    "--no-proxy"                        .. empty_arg,
    "--node-generic-resource"           .. empty_arg,
    "--oom-score-adjust"                .. empty_arg,
    "-p"                                .. file_matcher,
    "--pidfile"                         .. file_matcher,
    "--raw-logs",
    "--registry-mirror"                 .. empty_arg,
    "--rootless",
    "--seccomp-profile"                 .. seccomp_profiles,
    "--selinux-enabled",
    "--shutdown-timeout"                .. empty_arg,
    "-s"                                .. storage_drivers,
    "--storage-driver"                  .. storage_drivers,
    "--storage-opt"                     .. empty_arg,
    "--swarm-default-advertise-addr"    .. empty_arg,
    "--tls",
    "--tlscacert"                       .. file_matcher,
    "--tlscert"                         .. file_matcher,
    "--tlskey"                          .. file_matcher,
    "--tlsverify",
    "--userland-proxy",
    "--userland-proxy-path"             .. file_matcher,
    "--userns-remap"                    .. empty_arg,
    "-v",
    "--version",
    "--validate",
    "--cgroup-driver"                   .. cgroup_drivers,
})
