--------------------------------------------------------------------------------
-- Docker daemon (`dockerd`) completions for Clink.
--
-- https://docs.docker.com/reference/cli/dockerd/

-- luacheck: no max line length

--------------------------------------------------------------------------------
-- Value matchers for flags that accept arguments.

local log_levels = clink.argmatcher():addarg("debug", "info", "warn", "error", "fatal")
local log_drivers = clink.argmatcher():addarg({
    "none", "local", "json-file", "syslog", "journald", "gelf",
    "fluentd", "awslogs", "splunk", "etwlogs", "gcplogs", "logentries",
})
local storage_drivers = clink.argmatcher():addarg({
    "overlay2", "fuse-overlayfs", "btrfs", "zfs", "vfs",
})
local empty_arg = clink.argmatcher():addarg()
local file_matcher = clink.argmatcher():addarg(clink.filematches)
local dir_matcher = clink.argmatcher():addarg(clink.dirmatches)
local seccomp_profiles = file_matcher

-- REVIEW:  There seems to be no such flag as --cgroup-driver.  Documentation
-- says it's configured via `dockerd --exec-opt native.cgroupdriver=VALUE`.
--local cgroup_drivers = clink.argmatcher():addarg("cgroupfs", "systemd", "none")

--------------------------------------------------------------------------------
-- Main argmatcher.

local dockerd = clink.argmatcher("dockerd")

dockerd:adddescriptions({
    ["--add-runtime"]               = { " runtime", "注册额外的 OCI 兼容运行时" },
    ["--allow-nondistributable-artifacts"] = { " list", "允许将不可分发的制品推送到注册表" },
    ["--api-cors-header"]           = { " string", "设置 Engine API 中的 CORS 头" },
    ["--authorization-plugin"]      = { " list", "要加载的授权插件" },
    ["-b"]                          = { " string", "将容器附加到网络桥接" },
    ["--bridge"]                    = { " string", "将容器附加到网络桥接" },
    ["--bip"]                       = { " string", "指定网络桥接 IP" },
    -- REVIEW:  No such flag?  See note further above.
    --["--cgroup-driver"]             = { " string", "???" },
    ["--cgroup-parent"]             = { " string", "为所有容器设置父 cgroup" },
    ["--config-file"]               = { " string", "守护进程配置文件" },
    ["--containerd"]                = { " string", "containerd grpc 地址" },
    ["--containerd-namespace"]      = { " string", "要使用的 Containerd 命名空间" },
    ["--containerd-plugins-namespace"] = { " string", "用于插件的 Containerd 命名空间" },
    ["--cpu-rt-period"]             = { " int", "限制 CPU 实时周期（微秒）" },
    ["--cpu-rt-runtime"]            = { " int", "限制 CPU 实时运行时间（微秒）" },
    ["--cri-containerd"]            = { "使用 cri 启动 containerd" },
    ["-D"]                          = { "启用调试模式" },
    ["--debug"]                     = { "启用调试模式" },
    ["--data-root"]                 = { " string", "持久化 Docker 状态的根目录" },
    ["--default-address-pool"]      = { " list", "节点特定本地网络的默认地址池" },
    ["--default-cgroupns-mode"]     = { " string", "容器 cgroup 命名空间的默认模式" },
    ["--default-gateway"]           = { " ip", "容器默认网关 IPv4 地址" },
    ["--default-gateway-v6"]        = { " ip", "容器默认网关 IPv6 地址" },
    ["--default-ipc-mode"]          = { " string", "容器 ipc 的默认模式" },
    ["--default-network-opt"]       = { " map", "默认网络选项" },
    ["--default-runtime"]           = { " string", "容器的默认 OCI 运行时" },
    ["--default-shm-size"]          = { " bytes", "容器的默认 shm 大小" },
    ["--default-ulimit"]            = { " ulimit", "容器的默认 ulimits" },
    ["--dns"]                       = { " list", "要使用的 DNS 服务器" },
    ["--dns-opt"]                   = { " list", "要使用的 DNS 选项" },
    ["--dns-search"]                = { " list", "要使用的 DNS 搜索域" },
    ["--exec-opt"]                  = { " list", "运行时执行选项" },
    ["--exec-root"]                 = { " string", "执行状态文件的根目录" },
    ["--experimental"]              = { "启用实验性功能" },
    ["--fixed-cidr"]                = { " string", "固定 IP 的 IPv4 子网" },
    ["--fixed-cidr-v6"]             = { " string", "固定 IP 的 IPv6 子网" },
    ["-G"]                          = { " string", "unix socket 的组" },
    ["--group"]                     = { " string", "unix socket 的组" },
    ["-H"]                          = { " list", "要连接的守护进程 socket" },
    ["--host"]                      = { " list", "要连接的守护进程 socket" },
    ["--help"]                      = { "打印用法" },
    ["--http-proxy"]                = { " string", "拉取镜像的 HTTP 代理 URL" },
    ["--https-proxy"]               = { " string", "拉取镜像的 HTTPS 代理 URL" },
    ["--icc"]                       = { "启用容器间通信" },
    ["--init"]                      = { "在容器中运行 init 以转发信号和回收进程" },
    ["--init-path"]                 = { " string", "docker-init 二进制文件的路径" },
    ["--insecure-registry"]         = { " list", "启用不安全的注册表通信" },
    ["--ip"]                        = { " ip", "绑定容器端口时的默认 IP" },
    ["--ip-forward"]                = { "启用 net.ipv4.ip_forward" },
    ["--ip-masq"]                   = { "启用 IP 伪装" },
    ["--ip6tables"]                 = { "启用 ip6tables 规则添加" },
    ["--iptables"]                  = { "启用 iptables 规则添加" },
    ["--ipv6"]                      = { "启用 IPv6 网络" },
    ["-l"]                          = { " string", "设置日志级别" },
    ["--log-level"]                 = { " string", "设置日志级别" },
    ["--label"]                     = { " list", "为守护进程设置 key=value 标签" },
    ["--live-restore"]              = { "当容器仍在运行时启用 docker 的实时恢复" },
    ["--log-driver"]                = { " string", "容器日志的默认驱动" },
    ["--log-opt"]                   = { " map", "容器的默认日志驱动选项" },
    ["--max-concurrent-downloads"]  = { " int", "设置最大并发下载数" },
    ["--max-concurrent-uploads"]    = { " int", "设置最大并发上传数" },
    ["--max-download-attempts"]     = { " int", "设置每次拉取的最大下载尝试次数" },
    ["--metrics-addr"]              = { " string", "设置提供 metrics API 的默认地址和端口" },
    ["--mtu"]                       = { " int", "设置容器网络 MTU" },
    ["--network-control-plane-mtu"] = { " int", "网络控制平面 MTU" },
    ["--no-new-privileges"]         = { "默认对新容器设置 no-new-privileges" },
    ["--no-proxy"]                  = { " string", "跳过代理的主机或 IP 地址的逗号分隔列表" },
    ["--node-generic-resource"]     = { " list", "通告用户定义的资源" },
    ["--oom-score-adjust"]          = { " int", "设置守护进程的 oom_score_adj" },
    ["-p"]                          = { " string", "守护进程 PID 文件的路径" },
    ["--pidfile"]                   = { " string", "守护进程 PID 文件的路径" },
    ["--raw-logs"]                  = { "完整时间戳，不使用 ANSI 着色" },
    ["--registry-mirror"]           = { " list", "首选注册表镜像" },
    ["--rootless"]                  = { "启用无根模式" },
    ["--seccomp-profile"]           = { " string", "seccomp 配置文件的路径" },
    ["--selinux-enabled"]           = { "启用 selinux 支持" },
    ["--shutdown-timeout"]          = { " int", "设置默认关闭超时" },
    ["-s"]                          = { " string", "要使用的存储驱动" },
    ["--storage-driver"]            = { " string", "要使用的存储驱动" },
    ["--storage-opt"]               = { " list", "存储驱动选项" },
    ["--swarm-default-advertise-addr"] = { " string", "设置 swarm 通告地址的默认地址或接口" },
    ["--tls"]                       = { "使用 TLS；由 --tlsverify 隐含启用" },
    ["--tlscacert"]                 = { " string", "仅信任由此 CA 签名的证书" },
    ["--tlscert"]                   = { " string", "TLS 证书文件的路径" },
    ["--tlskey"]                    = { " string", "TLS 密钥文件的路径" },
    ["--tlsverify"]                 = { "使用 TLS 并验证远程" },
    ["--userland-proxy"]            = { "对回环流量使用用户态代理" },
    ["--userland-proxy-path"]       = { " string", "用户态代理二进制文件的路径" },
    ["--userns-remap"]              = { " string", "用户命名空间的用户/组设置" },
    ["-v"]                          = { "打印版本信息并退出" },
    ["--version"]                   = { "打印版本信息并退出" },
    ["--validate"]                  = { "验证守护进程配置并退出" },
})

dockerd:addflags({
    "--add-runtime"                     .. empty_arg,
    "--allow-nondistributable-artifacts" .. empty_arg,
    "--api-cors-header"                 .. empty_arg,
    "--authorization-plugin"            .. empty_arg,
    "-b"                                .. empty_arg,
    "--bridge"                          .. empty_arg,
    "--bip"                             .. empty_arg,
    -- REVIEW:  No such flag?  See note further above.
    --"--cgroup-driver"                   .. cgroup_drivers,
    "--cgroup-parent"                   .. empty_arg,
    "--config-file"                     .. file_matcher,
    "--containerd"                      .. empty_arg,
    "--containerd-namespace"            .. empty_arg,
    "--containerd-plugins-namespace"    .. empty_arg,
    "--cpu-rt-period"                   .. empty_arg,
    "--cpu-rt-runtime"                  .. empty_arg,
    "--cri-containerd",
    "-D",
    "--debug",
    "--data-root"                       .. dir_matcher,
    "--default-address-pool"            .. empty_arg,
    "--default-cgroupns-mode"           .. clink.argmatcher():addarg({"host", "private"}),
    "--default-gateway"                 .. empty_arg,
    "--default-gateway-v6"              .. empty_arg,
    "--default-ipc-mode"                .. clink.argmatcher():addarg({"shareable", "private"}),
    "--default-network-opt"             .. empty_arg,
    "--default-runtime"                 .. empty_arg,
    "--default-shm-size"                .. empty_arg,
    "--default-ulimit"                  .. empty_arg,
    "--dns"                             .. empty_arg,
    "--dns-opt"                         .. empty_arg,
    "--dns-search"                      .. empty_arg,
    "--exec-opt"                        .. empty_arg,
    "--exec-root"                       .. dir_matcher,
    "--experimental",
    "--fixed-cidr"                      .. empty_arg,
    "--fixed-cidr-v6"                   .. empty_arg,
    "-G"                                .. empty_arg,
    "--group"                           .. empty_arg,
    "-H"                                .. empty_arg,
    "--host"                            .. empty_arg,
    "--help",
    "--http-proxy"                      .. empty_arg,
    "--https-proxy"                     .. empty_arg,
    "--icc",
    "--init",
    "--init-path"                       .. file_matcher,
    "--insecure-registry"               .. empty_arg,
    "--ip"                              .. empty_arg,
    "--ip-forward",
    "--ip-masq",
    "--ip6tables",
    "--iptables",
    "--ipv6",
    "-l"                                .. log_levels,
    "--log-level"                       .. log_levels,
    "--label"                           .. empty_arg,
    "--live-restore",
    "--log-driver"                      .. log_drivers,
    "--log-opt"                         .. empty_arg,
    "--max-concurrent-downloads"        .. empty_arg,
    "--max-concurrent-uploads"          .. empty_arg,
    "--max-download-attempts"           .. empty_arg,
    "--metrics-addr"                    .. empty_arg,
    "--mtu"                             .. empty_arg,
    "--network-control-plane-mtu"       .. empty_arg,
    "--no-new-privileges",
    "--no-proxy"                        .. empty_arg,
    "--node-generic-resource"           .. empty_arg,
    "--oom-score-adjust"                .. empty_arg,
    "-p"                                .. file_matcher,
    "--pidfile"                         .. file_matcher,
    "--raw-logs",
    "--registry-mirror"                 .. empty_arg,
    "--rootless",
    "--seccomp-profile"                 .. seccomp_profiles,
    "--selinux-enabled",
    "--shutdown-timeout"                .. empty_arg,
    "-s"                                .. storage_drivers,
    "--storage-driver"                  .. storage_drivers,
    "--storage-opt"                     .. empty_arg,
    "--swarm-default-advertise-addr"    .. empty_arg,
    "--tls",
    "--tlscacert"                       .. file_matcher,
    "--tlscert"                         .. file_matcher,
    "--tlskey"                          .. file_matcher,
    "--tlsverify",
    "--userland-proxy",
    "--userland-proxy-path"             .. file_matcher,
    "--userns-remap"                    .. empty_arg,
    "-v",
    "--version",
    "--validate",
})
