-- Completions for fd (https://github.com/sharkdp/fd).

require("arghelper")

clink.argmatcher("fd"):_addexflags({
    { "--and",                   "Additional search patterns that need to be matched" },
    { "-d",                      "Set maximum search depth (default: none)" },
    { "--max-depth",             "Set maximum search depth (default: none)" },
    { "--min-depth",             "Only show search results starting at the given depth." },
    { "--exact-depth",           "Only show search results at the exact given depth" },
    { "-E",                      "Exclude entries that match the given glob pattern" },
    { "--exclude",               "Exclude entries that match the given glob pattern" },
    { "-t",                      "Filter by type: file (f), directory (d), symlink (l), executable (x), empty (e), socket (s), pipe (p), char-device (c), block-device (b)" },
    { "--type",                  "Filter by type: file (f), directory (d), symlink (l), executable (x), empty (e), socket (s), pipe (p), char-device (c), block-device (b)" },
    { "-e",                      "Filter by file extension" },
    { "--extension",             "Filter by file extension" },
    { "-S",                      "Limit results based on the size of files" },
    { "--size",                  "Limit results based on the size of files" },
    { "--changed-within",        "Filter by file modification time (newer than)" },
    { "--changed-before",        "Filter by file modification time (older than)" },
    { "-x",                      "Execute a command for each search result" },
    { "--exec",                  "Execute a command for each search result" },
    { "-X",                      "Execute a command with all search results at once" },
    { "--exec-batch",            "Execute a command with all search results at once" },
    { "--batch-size",            "Max number of arguments to run as a batch size with -X" },
    { "--ignore-file",           "Add a custom ignore-file in '.gitignore' format" },
    { "-c",                      "When to use colors" },
    { "--color",                 "When to use colors" },
    { "-j",                      "Set number of threads to use for searching & executing (default: number of available CPU cores)" },
    { "--threads",               "Set number of threads to use for searching & executing (default: number of available CPU cores)" },
    { "--max-buffer-time",       "Milliseconds to buffer before streaming search results to console" },
    { "--max-results",           "Limit the number of search results" },
    { "--base-directory",        "Change current working directory" },
    { "--path-separator",        "Set path separator when printing file paths" },
    { "--search-path",           "Provides paths to search as an alternative to the positional <path> argument" },
    { "--gen-completions",       "gen-completions" },
    { "-H",                      "Search hidden files and directories" },
    { "--hidden",                "Search hidden files and directories" },
    { "--no-hidden",             "Overrides --hidden" },
    { "-I",                      "Do not respect .(git|fd)ignore files" },
    { "--no-ignore",             "Do not respect .(git|fd)ignore files" },
    { "--ignore",                "Overrides --no-ignore" },
    { "--no-ignore-vcs",         "Do not respect .gitignore files" },
    { "--ignore-vcs",            "Overrides --no-ignore-vcs" },
    { "--no-require-git",        "Do not require a git repository to respect gitignores. By default, fd will only respect global gitignore rules, .gitignore rules, and local exclude rules if fd detects that you are searching inside a git repository. This flag allows you to relax this restriction such that fd will respect all git related ignore rules regardless of whether you're searching in a git repository or not" },
    { "--require-git",           "Overrides --no-require-git" },
    { "--no-ignore-parent",      "Do not respect .(git|fd)ignore files in parent directories" },
    { "--no-global-ignore-file", "Do not respect the global ignore file" },
    { "-u",                      "Unrestricted search, alias for '--no-ignore --hidden'" },
    { "--unrestricted",          "Unrestricted search, alias for '--no-ignore --hidden'" },
    { "-s",                      "Case-sensitive search (default: smart case)" },
    { "--case-sensitive",        "Case-sensitive search (default: smart case)" },
    { "-i",                      "Case-insensitive search (default: smart case)" },
    { "--ignore-case",           "Case-insensitive search (default: smart case)" },
    { "-g",                      "Glob-based search (default: regular expression)" },
    { "--glob",                  "Glob-based search (default: regular expression)" },
    { "--regex",                 "Regular-expression based search (default)" },
    { "-F",                      "Treat pattern as a literal string instead of regex" },
    { "--fixed-strings",         "Treat pattern as a literal string instead of regex" },
    { "-a",                      "Show absolute instead of relative paths" },
    { "--absolute-path",         "Show absolute instead of relative paths" },
    { "--relative-path",         "Overrides --absolute-path" },
    { "-l",                      "Use a long listing format with file metadata" },
    { "--list-details",          "Use a long listing format with file metadata" },
    { "-L",                      "Follow symbolic links" },
    { "--follow",                "Follow symbolic links" },
    { "--no-follow",             "Overrides --follow" },
    { "-p",                      "Search full abs. path (default: filename only)" },
    { "--full-path",             "Search full abs. path (default: filename only)" },
    { "-0",                      "Separate search results by the null character" },
    { "--print0",                "Separate search results by the null character" },
    { "--prune",                 "Do not traverse into directories that match the search criteria. If you want to exclude specific directories, use the '--exclude=…' option" },
    { "-1",                      "Limit search to a single result" },
    { "-q",                      "Print nothing, exit code 0 if match found, 1 otherwise" },
    { "--quiet",                 "Print nothing, exit code 0 if match found, 1 otherwise" },
    { "--show-errors",           "Show filesystem errors" },
    { "--strip-cwd-prefix",      "By default, relative paths are prefixed with './' when -x/--exec, -X/--exec-batch, or -0/--print0 are given, to reduce the risk of a path starting with '-' being treated as a command line option. Use this flag to disable this behavior" },
    { "--one-file-system",       "By default, fd will traverse the file system tree as far as other options dictate. With this flag, fd ensures that it does not descend into a different file system than the one it started in. Comparable to the -mount or -xdev filters of find(1)" },
    { "-h",                      "Print help (see more with '--help')" },
    { "--help",                  "Print help (see more with '--help')" },
    { "-V",                      "Print version" },
    { "--version",               "Print version" }
})
