--------------------------------------------------------------------------------
-- Clink argmatcher for ls (GNU coreutils)
--

clink.argmatcher("ls")
:addarg(clink.dirmatches)
:adddescriptions({
    ["-a"] = { "Do not ignore entries starting with ." },
    ["--all"] = { "Do not ignore entries starting with ." },
    ["-A"] = { "Do not list implied . and .." },
    ["--almost-all"] = { "Do not list implied . and .." },
    ["-l"] = { "Use a long listing format" },
    ["-h"] = { "Print sizes in human readable format (e.g., 1K 234M 2G)" },
    ["--human-readable"] = { "Print sizes in human readable format" },
    ["-r"] = { "Reverse order while sorting" },
    ["--reverse"] = { "Reverse order while sorting" },
    ["-t"] = { "Sort by modification time, newest first" },
    ["-S"] = { "Sort by file size, largest first" },
    ["--sort=size"] = { "Sort by file size, largest first" },
    ["-R"] = { "List subdirectories recursively" },
    ["--recursive"] = { "List subdirectories recursively" },
    ["-1"] = { "List one file per line" },
    ["-F"] = { "Append indicator (one of */=>@|) to entries" },
    ["--classify"] = { "Append indicator (one of */=>@|) to entries" },
    ["-d"] = { "List directories themselves, not their contents" },
    ["--directory"] = { "List directories themselves, not their contents" },
    ["-i"] = { "Print the inode number of each file" },
    ["--inode"] = { "Print the inode number of each file" },
    ["-L"] = { "Follow symbolic links, show info of target file" },
    ["--dereference"] = { "Follow symbolic links, show info of target file" },
    ["-p"] = { "Append / indicator to directories" },
    ["--indicator-style=slash"] = { "Append / indicator to directories" },
    ["-s"] = { "Print the allocated size of each file, in blocks" },
    ["--size"] = { "Print the allocated size of each file, in blocks" },
    ["-X"] = { "Sort alphabetically by entry extension" },
    ["--sort=extension"] = { "Sort alphabetically by entry extension" },
    ["-U"] = { "Do not sort; list entries in directory order" },
    ["--sort=none"] = { "Do not sort; list entries in directory order" },
    ["-v"] = { "Natural sort of version numbers within text" },
    ["--sort=version"] = { "Natural sort of version numbers within text" },
    ["-c"] = { "With -lt: sort by, and show, ctime" },
    ["-u"] = { "With -lt: sort by, and show, access time" },
    ["--color"] = { " arg", "Colorize the output: auto, always, never" },
    ["--help"] = { "Display help and exit" },
    ["--version"] = { "Output version information and exit" },
})
:addflags({
    "-a", "--all",
    "-A", "--almost-all",
    "-l",
    "-h", "--human-readable",
    "-r", "--reverse",
    "-t",
    "-S", "--sort=size",
    "-R", "--recursive",
    "-1",
    "-F", "--classify",
    "-d", "--directory",
    "-i", "--inode",
    "-L", "--dereference",
    "-p", "--indicator-style=slash",
    "-s", "--size",
    "-X", "--sort=extension",
    "-U", "--sort=none",
    "-v", "--sort=version",
    "-c", "-u",
    "--color="..(clink.argmatcher():addarg({"auto", "always", "never"})),
    "--help", "--version",
})
