--------------------------------------------------------------------------------
-- Clink argmatcher for pr (uutils / GNU coreutils)
--

local num_arg = clink.argmatcher():addarg({fromhistory=true})

clink.argmatcher("pr")
:addarg(clink.filematches)
:adddescriptions({
    ["-a"] = { "跨列打印（而非顺序列印）" },
    ["--across"] = { "跨列打印（而非顺序列印）" },
    ["-c"] = { " delimiter", "显示控制字符（使用脱字符表示法）" },
    ["--show-control-chars"] = { " delimiter", "显示控制字符（使用脱字符表示法）" },
    ["-d"] = { "输出行间距加倍" },
    ["--double-space"] = { "输出行间距加倍" },
    ["-D"] = { " format", "设置日期格式" },
    ["--date-format"] = { " format", "设置日期格式" },
    ["-e"] = { " tab-width", "将制表符扩展为空格（指定制表符宽度）" },
    ["--expand-tabs"] = { " tab-width", "将制表符扩展为空格（指定制表符宽度）" },
    ["-f"] = { "使用换页符（而非换行符）分隔页面" },
    ["--form-feed"] = { "使用换页符（而非换行符）分隔页面" },
    ["-F"] = { "使用换页符（而非换行符）分隔页面（同 -f）" },
    ["-h"] = { " header", "设置页眉文字" },
    ["--header"] = { " header", "设置页眉文字" },
    ["-i"] = { " tab-width", "将空格替换为制表符（指定停止位）" },
    ["--output-tabs"] = { " tab-width", "将空格替换为制表符（指定停止位）" },
    ["-J"] = { "合并全部行（不截断）" },
    ["--join-lines"] = { "合并全部行（不截断）" },
    ["-l"] = { " length", "页面行数（默认 66）" },
    ["--length"] = { " length", "页面行数（默认 66）" },
    ["-m"] = { "并行打印所有文件（每列一个文件）" },
    ["--merge"] = { "并行打印所有文件（每列一个文件）" },
    ["-n"] = { " separator,digits", "为每行添加行号" },
    ["--number-lines"] = { " separator,digits", "为每行添加行号" },
    ["-N"] = { " number-lines", "为每行添加行号" },
    ["-o"] = { " margin", "设置左缩进宽度" },
    ["--indent"] = { " margin", "设置左缩进宽度" },
    ["-r"] = { "禁止文件无法打开时的警告" },
    ["--no-file-warnings"] = { "禁止文件无法打开时的警告" },
    ["-s"] = { " separator", "设置列分隔符" },
    ["--separator"] = { " separator", "设置列分隔符" },
    ["-S"] = { " string", "设置列分隔字符串" },
    ["--sep-string"] = { " string", "设置列分隔字符串" },
    ["-t"] = { "省略页眉和页尾" },
    ["--omit-header"] = { "省略页眉和页尾" },
    ["-T"] = { "省略分页（忽略换页符）" },
    ["--omit-pagination"] = { "省略分页（忽略换页符）" },
    ["-v"] = { "以脱字符表示法显示不可打印字符" },
    ["--show-nonprinting"] = { "以脱字符表示法显示不可打印字符" },
    ["-w"] = { " width", "页面宽度（默认 72）" },
    ["--width"] = { " width", "页面宽度（默认 72）" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
})
:addflags({
    "-a", "--across",
    "-c",
    "--show-control-chars=",
    "-d", "--double-space",
    "-D",
    "--date-format=",
    "-e"..num_arg,
    "--expand-tabs="..num_arg,
    "-f", "--form-feed",
    "-F",
    "-h",
    "--header=",
    "-i"..num_arg,
    "--output-tabs="..num_arg,
    "-J", "--join-lines",
    "-l"..num_arg,
    "--length="..num_arg,
    "-m", "--merge",
    "-n",
    "--number-lines=",
    "-N"..num_arg,
    "-o"..num_arg,
    "--indent="..num_arg,
    "-r", "--no-file-warnings",
    "-s",
    "--separator=",
    "-S",
    "--sep-string=",
    "-t", "--omit-header",
    "-T", "--omit-pagination",
    "-v", "--show-nonprinting",
    "-w"..num_arg,
    "--width="..num_arg,
    "--help", "--version",
})
