--------------------------------------------------------------------------------
-- Clink argmatcher for ptx (uutils / GNU coreutils)
--

local num_arg = clink.argmatcher():addarg({fromhistory=true})

clink.argmatcher("ptx")
:addarg(clink.filematches)
:adddescriptions({
    ["-A"] = { " prefix", "自动生成引用的前缀" },
    ["--auto-reference"] = { " prefix", "自动生成引用的前缀" },
    ["-G"] = { "传统输出格式" },
    ["--traditional"] = { "传统输出格式" },
    ["-F"] = { " string", "标记行尾截断的字符串" },
    ["--flag-truncation"] = { " string", "标记行尾截断的字符串" },
    ["-M"] = { " name", "定义宏名称" },
    ["--macro-name"] = { " name", "定义宏名称" },
    ["-O"] = { "roff 格式输出" },
    ["--format=roff"] = { "roff 格式输出" },
    ["-R"] = { " references", "引用位置：left 或 right" },
    ["--references"] = { " references", "引用位置：left 或 right" },
    ["-S"] = { " regexp", "句子结束的正则表达式" },
    ["--sentence-regexp"] = { " regexp", "句子结束的正则表达式" },
    ["-T"] = { "TeX 格式输出" },
    ["--format=tex"] = { "TeX 格式输出" },
    ["-W"] = { " regexp", "单词匹配的正则表达式" },
    ["--word-regexp"] = { " regexp", "单词匹配的正则表达式" },
    ["-b"] = { " file", "从文件中读取忽略词" },
    ["--break-file"] = { " file", "从文件中读取忽略词" },
    ["-f"] = { "忽略大小写进行排序" },
    ["--ignore-case"] = { "忽略大小写进行排序" },
    ["-g"] = { " num", "合并词之间允许的最小间距" },
    ["--gap-size"] = { " num", "合并词之间允许的最小间距" },
    ["-i"] = { " file", "从文件中读取忽略词" },
    ["--ignore-file"] = { " file", "从文件中读取忽略词" },
    ["-o"] = { " file", "仅使用文件中列出的词作为关键词" },
    ["--only-file"] = { " file", "仅使用文件中列出的词作为关键词" },
    ["-r"] = { " field", "将引用之前的字段（而非整行）作为引用" },
    ["-t"] = { " 排版模式输出" },
    ["--typeset-mode"] = { " 排版模式输出" },
    ["-w"] = { " num", "输出宽度" },
    ["--width"] = { " num", "输出宽度" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
})
:addflags({
    "-A",
    "--auto-reference=",
    "-G", "--traditional",
    "-F",
    "--flag-truncation=",
    "-M",
    "--macro-name=",
    "-O", "--format=roff",
    "-R",
    "--references="..(clink.argmatcher():addarg({"left", "right"})),
    "-S",
    "--sentence-regexp=",
    "-T", "--format=tex",
    "-W",
    "--word-regexp=",
    "-b"..(clink.argmatcher():addarg(clink.filematches)),
    "--break-file="..(clink.argmatcher():addarg(clink.filematches)),
    "-f", "--ignore-case",
    "-g"..num_arg,
    "--gap-size="..num_arg,
    "-i"..(clink.argmatcher():addarg(clink.filematches)),
    "--ignore-file="..(clink.argmatcher():addarg(clink.filematches)),
    "-o"..(clink.argmatcher():addarg(clink.filematches)),
    "--only-file="..(clink.argmatcher():addarg(clink.filematches)),
    "-r"..num_arg,
    "-t", "--typeset-mode",
    "-w"..num_arg,
    "--width="..num_arg,
    "--help", "--version",
})
