-- Completions for ripgrep (https://github.com/BurntSushi/ripgrep).

require("arghelper")

clink.argmatcher("rg"):_addexflags({
    -- INPUT OPTIONS:
    { "-e",                             "A pattern to search for." },
    { "--regexp=PATTERN",               "A pattern to search for." },
    { "-f",                             "Search for patterns from the given file." },
    { "--file=PATTERNFILE",             "Search for patterns from the given file." },
    { "--pre=COMMAND",                  "Search output of COMMAND for each PATH." },
    { "--pre-glob=GLOB",                "Include or exclude files from a preprocessor." },
    { "-z",                             "Search in compressed files." },
    { "--search-zip",                   "Search in compressed files." },

    -- SEARCH OPTIONS:
    { "-s",                             "Search case sensitively (default)." },
    { "--case-sensitive",               "Search case sensitively (default)." },
    { "--crlf",                         "Use CRLF line terminators (nice for Windows)." },
    { "--dfa-size-limit=NUM",           "The upper size limit of the regex DFA." },
    { "-E",                             "Specify the text encoding of files to search." },
    { "--encoding=ENCODING",            "Specify the text encoding of files to search." },
    { "--engine=ENGINE",                "Specify which regex engine to use." },
    { "-F",                             "Treat all patterns as literals." },
    { "--fixed-strings",                "Treat all patterns as literals." },
    { "-i",                             "Case insensitive search." },
    { "--ignore-case",                  "Case insensitive search." },
    { "-v",                             "Invert matching." },
    { "--invert-match",                 "Invert matching." },
    { "-x",                             "Show matches surrounded by line boundaries." },
    { "--line-regexp",                  "Show matches surrounded by line boundaries." },
    { "-m",                             "Limit the number of matching lines." },
    { "--max-count=NUM",                "Limit the number of matching lines." },
    { "--mmap",                         "Search with memory maps when possible." },
    { "-U",                             "Enable searching across multiple lines." },
    { "--multiline",                    "Enable searching across multiple lines." },
    { "--multiline-dotall",             "Make '.' match line terminators." },
    { "--no-unicode",                   "Disable Unicode mode." },
    { "--null-data",                    "Use NUL as a line terminator." },
    { "-P",                             "Enable PCRE2 matching." },
    { "--pcre2",                        "Enable PCRE2 matching." },
    { "--regex-size-limit=NUM",         "The size limit of the compiled regex." },
    { "-S",                             "Smart case search." },
    { "--smart-case",                   "Smart case search." },
    { "--stop-on-nonmatch",             "Stop searching after a non-match." },
    { "-a",                             "Search binary files as if they were text." },
    { "--text",                         "Search binary files as if they were text." },
    { "-j",                             "Set the approximate number of threads to use." },
    { "--threads=NUM",                  "Set the approximate number of threads to use." },
    { "-w",                             "Show matches surrounded by word boundaries." },
    { "--word-regexp",                  "Show matches surrounded by word boundaries." },
    { "--auto-hybrid-regex",            "(DEPRECATED) Use PCRE2 if appropriate." },
    { "--no-pcre2-unicode",             "(DEPRECATED) Disable Unicode mode for PCRE2." },

    -- FILTER OPTIONS:
    { "--binary",                       "Search binary files." },
    { "-L",                             "Follow symbolic links." },
    { "--follow",                       "Follow symbolic links." },
    { "-g",                             "Include or exclude file paths." },
    { "--glob=GLOB",                    "Include or exclude file paths." },
    { "--glob-case-insensitive",        "Process all glob patterns case insensitively." },
    { "-.",                             "Search hidden files and directories." },
    { "--hidden",                       "Search hidden files and directories." },
    { "--iglob=GLOB",                   "Include/exclude paths case insensitively." },
    { "--ignore-file=PATH",             "Specify additional ignore files." },
    { "--ignore-file-case-insensitive", "Process ignore files case insensitively." },
    { "-d",                             "Descend at most NUM directories." },
    { "--max-depth=NUM",                "Descend at most NUM directories." },
    { "--max-filesize=NUM",             "Ignore files larger than NUM in size." },
    { "--no-ignore",                    "Don't use ignore files." },
    { "--no-ignore-dot",                "Don't use .ignore or .rgignore files." },
    { "--no-ignore-exclude",            "Don't use local exclusion files." },
    { "--no-ignore-files",              "Don't use --ignore-file arguments." },
    { "--no-ignore-global",             "Don't use global ignore files." },
    { "--no-ignore-parent",             "Don't use ignore files in parent directories." },
    { "--no-ignore-vcs",                "Don't use ignore files from source control." },
    { "--no-require-git",               "Use .gitignore outside of git repositories." },
    { "--one-file-system",              "Skip directories on other file systems." },
    { "-t",                             "Only search files matching TYPE." },
    { "--type=TYPE",                    "Only search files matching TYPE." },
    { "-T",                             "Do not search files matching TYPE." },
    { "--type-not=TYPE",                "Do not search files matching TYPE." },
    { "--type-add=TYPESPEC",            "Add a new glob for a file type." },
    { "--type-clear=TYPE",              "Clear globs for a file type." },
    { "-u",                             "Reduce the level of \"smart\" filtering." },
    { "--unrestricted",                 "Reduce the level of \"smart\" filtering." },

    -- OUTPUT OPTIONS:
    { "-A",                             "Show NUM lines after each match." },
    { "--after-context=NUM",            "Show NUM lines after each match." },
    { "-B",                             "Show NUM lines before each match." },
    { "--before-context=NUM",           "Show NUM lines before each match." },
    { "--block-buffered",               "Force block buffering." },
    { "-b",                             "Print the byte offset for each matching line." },
    { "--byte-offset",                  "Print the byte offset for each matching line." },
    { "--color=WHEN",                   "When to use color." },
    { "--colors=COLOR_SPEC",            "Configure color settings and styles." },
    { "--column",                       "Show column numbers." },
    { "-C",                             "Show NUM lines before and after each match." },
    { "--context=NUM",                  "Show NUM lines before and after each match." },
    { "--context-separator=SEP",        "Set the separator for contextual chunks." },
    { "--field-context-separator=SEP",  "Set the field context separator." },
    { "--field-match-separator=SEP",    "Set the field match separator." },
    { "--heading",                      "Print matches grouped by each file." },
    { "-h",                             "Show help output." },
    { "--help",                         "Show help output." },
    { "--hostname-bin=COMMAND",         "Run a program to get this system's hostname." },
    { "--hyperlink-format=FORMAT",      "Set the format of hyperlinks." },
    { "--include-zero",                 "Include zero matches in summary output." },
    { "--line-buffered",                "Force line buffering." },
    { "-n",                             "Show line numbers." },
    { "--line-number",                  "Show line numbers." },
    { "-N",                             "Suppress line numbers." },
    { "--no-line-number",               "Suppress line numbers." },
    { "-M",                             "Omit lines longer than this limit." },
    { "--max-columns=NUM",              "Omit lines longer than this limit." },
    { "--max-columns-preview",          "Show preview for lines exceeding the limit." },
    { "-0",                             "Print a NUL byte after file paths." },
    { "--null",                         "Print a NUL byte after file paths." },
    { "-o",                             "Print only matched parts of a line." },
    { "--only-matching",                "Print only matched parts of a line." },
    { "--path-separator=SEP",           "Set the path separator for printing paths." },
    { "--passthru",                     "Print both matching and non-matching lines." },
    { "-p",                             "Alias for colors, headings and line numbers." },
    { "--pretty",                       "Alias for colors, headings and line numbers." },
    { "-q",                             "Do not print anything to stdout." },
    { "--quiet",                        "Do not print anything to stdout." },
    { "-r",                             "Replace matches with the given text." },
    { "--replace=TEXT",                 "Replace matches with the given text." },
    { "--sort=SORTBY",                  "Sort results in ascending order." },
    { "--sortr=SORTBY",                 "Sort results in descending order." },
    { "--trim",                         "Trim prefix whitespace from matches." },
    { "--vimgrep",                      "Print results in a vim compatible format." },
    { "-H",                             "Print the file path with each matching line." },
    { "--with-filename",                "Print the file path with each matching line." },
    { "-I",                             "Never print the path with each matching line." },
    { "--no-filename",                  "Never print the path with each matching line." },
    { "--sort-files",                   "(DEPRECATED) Sort results by file path." },

    -- OUTPUT MODES:
    { "-c",                             "Show count of matching lines for each file." },
    { "--count",                        "Show count of matching lines for each file." },
    { "--count-matches",                "Show count of every match for each file." },
    { "-l",                             "Print the paths with at least one match." },
    { "--files-with-matches",           "Print the paths with at least one match." },
    { "--files-without-match",          "Print the paths that contain zero matches." },
    { "--json",                         "Show search results in a JSON Lines format." },

    -- LOGGING OPTIONS:
    { "--debug",                        "Show debug messages." },
    { "--no-ignore-messages",           "Suppress gitignore parse error messages." },
    { "--no-messages",                  "Suppress some error messages." },
    { "--stats",                        "Print statistics about the search." },
    { "--trace",                        "Show trace messages." },

    -- OTHER BEHAVIORS:
    { "--files",                        "Print each file that would be searched." },
    { "--generate=KIND",                "Generate man pages and completion scripts." },
    { "--no-config",                    "Never read configuration files." },
    { "--pcre2-version",                "Print the version of PCRE2 that ripgrep uses." },
    { "--type-list",                    "Show all supported file types." },
    { "-V",                             "Print ripgrep's version." },
    { "--version",                      "Print ripgrep's version." }
})
