--------------------------------------------------------------------------------
-- Clink argmatcher for sort (uutils / GNU coreutils)
--

local num_arg = clink.argmatcher():addarg({fromhistory=true})

clink.argmatcher("sort")
:addarg(clink.filematches)
:adddescriptions({
    ["-b"] = { "忽略前导空白" },
    ["--ignore-leading-blanks"] = { "忽略前导空白" },
    ["-c"] = { "检查是否已排序，不排序" },
    ["--check"] = { "检查是否已排序，不排序" },
    ["-C"] = { "静默检查是否已排序，不输出" },
    ["--check=quiet"] = { "静默检查是否已排序，不输出" },
    ["-d"] = { "仅考虑空白、字母和数字字符" },
    ["--dictionary-order"] = { "仅考虑空白、字母和数字字符" },
    ["-f"] = { "忽略大小写" },
    ["--ignore-case"] = { "忽略大小写" },
    ["-g"] = { "按数值排序，支持科学计数法" },
    ["--general-numeric-sort"] = { "按数值排序，支持科学计数法" },
    ["-h"] = { "按人类可读数值排序（如 2K 1G）" },
    ["--human-numeric-sort"] = { "按人类可读数值排序（如 2K 1G）" },
    ["-i"] = { "仅考虑可打印字符" },
    ["--ignore-nonprinting"] = { "仅考虑可打印字符" },
    ["-k"] = { " KEYDEF", "按 KEYDEF 指定的键排序" },
    ["--key"] = { " KEYDEF", "按 KEYDEF 指定的键排序" },
    ["-M"] = { "按月份排序（JAN < ... < DEC）" },
    ["--month-sort"] = { "按月份排序（JAN < ... < DEC）" },
    ["-n"] = { "按数值排序" },
    ["--numeric-sort"] = { "按数值排序" },
    ["-R"] = { "随机排序" },
    ["--random-sort"] = { "随机排序" },
    ["-r"] = { "反转排序结果" },
    ["--reverse"] = { "反转排序结果" },
    ["-o"] = { " FILE", "将结果写入 FILE 而非标准输出" },
    ["--output"] = { " FILE", "将结果写入 FILE 而非标准输出" },
    ["-s"] = { "禁用最后的比较以稳定排序" },
    ["--stable"] = { "禁用最后的比较以稳定排序" },
    ["-S"] = { " SIZE", "指定主内存缓冲区大小" },
    ["--buffer-size"] = { " SIZE", "指定主内存缓冲区大小" },
    ["-t"] = { " SEP", "使用 SEP 作为字段分隔符" },
    ["--field-separator"] = { " SEP", "使用 SEP 作为字段分隔符" },
    ["-T"] = { " DIR", "使用 DIR 作为临时文件目录" },
    ["--temporary-directory"] = { " DIR", "使用 DIR 作为临时文件目录" },
    ["-u"] = { "输出时去除重复行" },
    ["--unique"] = { "输出时去除重复行" },
    ["-z"] = { "用 NUL 字节终止行" },
    ["--zero-terminated"] = { "用 NUL 字节终止行" },
    ["-m"] = { "合并已排序的文件，不排序" },
    ["--merge"] = { "合并已排序的文件，不排序" },
    ["--debug"] = { "标注用于排序的行部分" },
    ["--parallel"] = { " N", "设置同时运行的排序线程数" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
})
:addflags({
    "-b", "--ignore-leading-blanks",
    "-c", "--check",
    "-C", "--check=quiet",
    "-d", "--dictionary-order",
    "-f", "--ignore-case",
    "-g", "--general-numeric-sort",
    "-h", "--human-numeric-sort",
    "-i", "--ignore-nonprinting",
    "-k", "--key",
    "-M", "--month-sort",
    "-n", "--numeric-sort",
    "-R", "--random-sort",
    "-r", "--reverse",
    "-o"..(clink.argmatcher():addarg(clink.filematches)),
    "--output="..(clink.argmatcher():addarg(clink.filematches)),
    "-s", "--stable",
    "-S"..num_arg, "--buffer-size="..num_arg,
    "-t", "--field-separator",
    "-T"..(clink.argmatcher():addarg(clink.dirmatches)),
    "--temporary-directory="..(clink.argmatcher():addarg(clink.dirmatches)),
    "-u", "--unique",
    "-z", "--zero-terminated",
    "-m", "--merge",
    "--debug",
    "--parallel="..num_arg,
    "--help", "--version",
})
