--------------------------------------------------------------------------------
-- Clink argmatcher for xargs (uutils / GNU coreutils)
--

local num_arg = clink.argmatcher():addarg({fromhistory=true})

clink.argmatcher("xargs")
:adddescriptions({
    ["-a"] = { " file", "从文件而非标准输入读取参数" },
    ["--arg-file"] = { " file", "从文件而非标准输入读取参数" },
    ["-0"] = { "输入项以 NUL 字符分隔（非空白字符）" },
    ["--null"] = { "输入项以 NUL 字符分隔（非空白字符）" },
    ["-d"] = { " delim", "设置输入分隔符" },
    ["--delimiter"] = { " delim", "设置输入分隔符" },
    ["-E"] = { " str", "当遇到 str 时结束输入" },
    ["--eof-str"] = { " str", "当遇到 str 时结束输入" },
    ["-I"] = { " replace-str", "将 replace-str 替换为从标准输入读取的参数" },
    ["--replace"] = { " replace-str", "将 replace-str 替换为从标准输入读取的参数" },
    ["-i"] = { " 等同于 -I{}（已弃用）" },
    ["-L"] = { " max-lines", "每次调用命令最多使用 max-lines 行输入" },
    ["--max-lines"] = { " max-lines", "每次调用命令最多使用 max-lines 行输入" },
    ["-l"] = { " max-lines", "等同于 -L max-lines（已弃用）" },
    ["-n"] = { " max-args", "每次调用命令最多使用 max-args 个参数" },
    ["--max-args"] = { " max-args", "每次调用命令最多使用 max-args 个参数" },
    ["-o"] = { "在子进程中打开 /dev/tty 作为标准输入" },
    ["--open-tty"] = { "在子进程中打开 /dev/tty 作为标准输入" },
    ["-P"] = { " max-procs", "同时运行最多 max-procs 个进程" },
    ["--max-procs"] = { " max-procs", "同时运行最多 max-procs 个进程" },
    ["-p"] = { "执行每个命令前提示确认" },
    ["--interactive"] = { "执行每个命令前提示确认" },
    ["--process-slot-var"] = { " name", "将子进程编号存入环境变量 name" },
    ["-r"] = { "如果标准输入为空则不执行命令" },
    ["--no-run-if-empty"] = { "如果标准输入为空则不执行命令" },
    ["-s"] = { " max-chars", "设置命令行的最大字符数" },
    ["--max-chars"] = { " max-chars", "设置命令行的最大字符数" },
    ["-t"] = { "执行前打印命令行" },
    ["--verbose"] = { "执行前打印命令行" },
    ["-x"] = { "如果命令行超过系统限制则退出" },
    ["--exit"] = { "如果命令行超过系统限制则退出" },
    ["--show-limits"] = { "显示系统对命令行的限制" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
})
:addflags({
    "-a"..(clink.argmatcher():addarg(clink.filematches)),
    "--arg-file="..(clink.argmatcher():addarg(clink.filematches)),
    "-0", "--null",
    "-d",
    "--delimiter=",
    "-E",
    "--eof-str=",
    "-I",
    "--replace=",
    "-i",
    "-L"..num_arg,
    "--max-lines="..num_arg,
    "-l"..num_arg,
    "-n"..num_arg,
    "--max-args="..num_arg,
    "-o", "--open-tty",
    "-P"..num_arg,
    "--max-procs="..num_arg,
    "-p", "--interactive",
    "--process-slot-var=",
    "-r", "--no-run-if-empty",
    "-s"..num_arg,
    "--max-chars="..num_arg,
    "-t", "--verbose",
    "-x", "--exit",
    "--show-limits",
    "--help", "--version",
})
